### ISSUE TITLE
Not actually lightweight ;)

### ISSUE THREAD

**Issue by panasenco** [myshell-ai/AIlice#26]
The tagline of AIlice is 'lightweight AI agent', and while the code itself is brilliantly minimal, the ailice virtual environment took up 5.8GB of space on my hard drive.

The biggest contributors to the size are the `nvidia` package at 2.8GB and `torch` at 1.6GB.

Would it be possible to not depend on these packages, or to make the dependencies optional?

**Comment by stevenlu137** [comment]
I've also been constantly trying to strip away unnecessary dependencies. Currently, the most ideal approach is to make the default installation independent of transformers and torch. However, at the moment, I'm temporarily constrained by the implementation of the vector database (which is essential for AIlice). I plan to investigate this issue first to see if we can further reduce these dependencies.

**Comment by stevenlu137** [comment]
I have removed the default dependencies on the huggingface stack and torch in the latest version of the master branch. However, this brings some issues, such as needing to disable Hyper-V for installation in virtual machines, otherwise, it will fail. We will address these issues once we establish a long-term memory mechanism. 

Of course, we also have a last resort to solve this problem by changing the project description to something like "an autonomous general multi-agent framework," haha.

**Comment by stevenlu137** [comment]
We have finally removed the dependency on Gradio. Now, the default dependencies installed with AIlice have been minimized. This issue can be temporarily closed.
