### ISSUE TITLE
💡 Rewrite it in https://www.modular.com/mojo, a python compatible new lang, for c++ performance?

### ISSUE THREAD

**Issue by jechaviz** [myshell-ai/AIlice#53]
This lang was created to use all cpus available in a machine with c like performance but using a pythonic lang completely compatible with python, for the new ai era.

![image](https://github.com/user-attachments/assets/35a54b4f-3372-457f-b066-e0d81ed39783)
It has true interoperability with the Python ecosystem. 
Read introduction for more info:
https://docs.modular.com/mojo/manual/
So it theory, it can be improve speed like 68k times.

**Comment by stevenlu137** [comment]
Hello, if you experience low performance during use, please first refer to the **Accelerate using GPU** section in the README to set up using GPU to perform calculations related to the vector database. CPU is used by default here, which will cause slow operation, but for compatibility For more machines that do not have a cuda runtime environment, we will set it as the default behavior (automatic selection of computing devices is a better strategy, and I will continue to improve it).

At present, most of the running time of AIlice is consumed in the inference operations in LLM and embedded models of vector databases, rather than in the Python code itself, so we are not considering re-implementing it in a new language for now. Since LLM's inference can be solved using various high-speed inference solutions, our main optimization target is the embedded model. The current solution using llama-cpp-python cannot automatically select computing devices, and result in frequent installation failures. The tensor compiler seems like a tempting solution and I'm still looking for ways to improve this.

**Comment by jechaviz** [comment]
Thank you.
